### ISSUE TITLE
Error when hovering over “unstable” option

### ISSUE THREAD

**Issue by LucyferHW** [M3ales/MIRA_Vehicle_Medical#25]
We have a problem while using the mod.
When we hover over "unstable" option, we get an error message (see picture).
The Error says "Error zero divisor".

When you need more information about what and when is happening, I can update this report.

![MedicalError](https://user-images.githubusercontent.com/50595135/227395005-14df1674-132e-4e15-a508-feb7ed004136.png)

**Comment by M3ales** [comment]
~~Are you able to attach your rpt after the error please?~~

This was fixed by #23, but this hasn't made it into the wild yet. This issue should just be something that shows once in the editor? If it's impacting gameplay then I can push something out with it -- but my only experience of it is within eden.

**Comment by LucyferHW** [comment]
We have this Error inside Missions. Like described earlier it is every time we hover over the button.

Could you be so kind and push a fix for the bug.
I can help with logs or more information.

**Comment by M3ales** [comment]
[2.5.0](https://github.com/M3ales/MIRA_Vehicle_Medical/releases/tag/2.5.0)
